// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaKcF6lqNg7q6ANFTwpkOUsiYlA5kXNfQ',
    appId: '1:795103154834:android:e807d93ff201cd5c2e4c4b',
    messagingSenderId: '795103154834',
    projectId: 'chatting-app-nt109n21',
    storageBucket: 'chatting-app-nt109n21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhE11gQTOsh5ne7x-2W4dGBaPaI_Csohk',
    appId: '1:795103154834:ios:524c2c9c8d3cbf882e4c4b',
    messagingSenderId: '795103154834',
    projectId: 'chatting-app-nt109n21',
    storageBucket: 'chatting-app-nt109n21.appspot.com',
    androidClientId: '795103154834-jrj9vjchkqsn75qpha2q9jd0ocs2vtlf.apps.googleusercontent.com',
    iosClientId: '795103154834-bdvr74nc2k93ccnp3qro97mi7h66ckno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingAppNt109n21',
  );
}
